[build_system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "xarray_bitpacker"
authors = [{"name"="Lander Ver Hoef", "email"="Lander.Ver_Hoef@colostate.edu"}]
description = "Xarray extension that leverages xarray's metadata to automate and enhance numpy's bitpacking functionality."
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.11"
dynamic = ["version"]
license = "Apache-2.0"
license-files = ["LICENSE"]
dependencies = ["numpy", "xarray"]

[project.urls]
Homepage = "https://github.com/zyjux/xarray_bitpacker"
Issues = "https://github.com/zyjux/xarray_bitpacker/issues"

[tool.setuptools.dynamic]
version = {attr = "xarray_bitpacker.__version__"}
